#use_frameworks!

platform :ios, '9.0'

target 'CommonSettingSwift_Example' do
  pod 'CommonSettingSwift', :path => '../'

  target 'CommonSettingSwift_Tests' do
    inherit! :search_paths

    
  end
end
